# Generated by Django 6.0.3 on 2026-03-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_address_coupon_order_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totla_price',
            new_name='total_price',
        ),
    ]
